[project]
name = "analysis-of-animal-language"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.78.0",
    "transformers>=4.51.3",
]
